#!/bin/bash
# A user logs in with a client-side certificate and receives a single encrypted message which is then deleted from the server. 
# The recipient uses the sender's certificate to verify the signature on the message, decrypt the message, and finally display the message.
# For example, if the certificate is at certs/starshine.cert.pem, 
# Run like ./recvmsg -u starshine -c starshine.cert.pem

while getopts u:c: flag
do
    case "${flag}" in
        u) USERNAME=${OPTARG};;
        c) CERTIFICATE=${OPTARG};;
    esac
done

echo "Username: $USERNAME";
echo "Certificate: $CERTIFICATE"

#Actually use the client
./src/https_client RECVMSG $USERNAME $CERTIFICATE
