#!/bin/bash
# The user will supply a -u username, -m message and -c certificate filename, which should be stored in the certs/ directory.
# Use the -r flag for each recipient.
# For example, if the certificate is at certs/starshine.cert.pem, 
# Run like ./sendmsg -u starshine -m "Hello World!" -c starshine.cert.pem -r Ava -r Mark -r Monica -r Yasemin

while getopts u:m:c:r: flag
do
    case "${flag}" in
        u) USERNAME=${OPTARG};;
        m) MESSAGE=${OPTARG};;
        c) CERTIFICATE=${OPTARG};;
        r) RCPTS+=("$OPTARG");;
    esac
done
shift $((OPTIND -1))

echo "Username: $USERNAME";
echo "Reading certificate from: certs/$CERTIFICATE";
echo "Sending message: $MESSAGE";
echo "Recipients:";
for val in "${RCPTS[@]}"; do
    echo " - $val"
done
