#!/bin/bash
#invoke as sudo for chown to work.

#Set permissions on a folder with this username
USERNAME="$1"; 
cd ../..
# this user should be able to access their own folder.
chown $USERNAME $USERNAME/
chmod u=rx,g=,o= $USERNAME/


