#!/bin/bash

if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit 1
fi

#Will clone this parent directory and make a client directory with the given name and populate it
#run like ./make_client starshine
USERNAME="$1"; 
cp -r ../ ../../$1
cd ../../$1/scripts
./client_setup

rm ../src/https_client.cpp 
rm client_setup
rm make_client