#!/bin/bash

# Go into security project folder
cd ..

# Setup server
cd server
make
cd scripts
./create-filesystem
./ca_setup
make
cd ..

# Run server
./https_server CA/intermediate/certs/www.finalproject.com.cert.pem CA/intermediate/private/www.finalproject.com.key.pem CA/intermediate/certs/ca-chain.cert.pem 2>&1 &
echo $! > ../server.pid
sleep 3

# Set up clients
cd ../client/scripts
./make_client polypose

# Go into polypose
cd ../../polypose

# get a certificate
./getcert -u polypose -p lure_leagued
sleep 3

# send message from polypose to polypose
./sendmsg -u polypose -m 'Yellow World!' -c mycert.cert.pem -r polypose
sleep 3

# receive message, valid cert
STR=$(./recvmsg -u polypose -c mycert.cert.pem)
sleep 3

SUB="Yellow World!"
# check if the message got received
if [[ "$STR" == *"$SUB"* ]]; then
    echo -e ' \xE2\x9C\x85\tRECVMSG TEST 0 PASSED\t\xE2\x9C\x85 \n' >> ../test_cases/very_secure_results.txt
else
    echo -e "-------------------------------RECVMSG TEST 0 FAILED.-------------------------------\n" >> ../test_cases/very_secure_results.txt
fi

# Clean up clients
cd ..
rm -rf polypose

# Clean up server
pkill -F server.pid
rm -f server.pid

# Clean up server
cd server/scripts
make clean
cd ..
rm -rf CA filesystem tmp
make clean

# Go back to test folder
cd ../test_cases