#!/bin/bash

# Go into security project folder
cd ..

# Setup server
cd server
make
cd scripts
./create-filesystem
./ca_setup
make
cd ..

# Run server
./https_server CA/intermediate/certs/www.finalproject.com.cert.pem CA/intermediate/private/www.finalproject.com.key.pem CA/intermediate/certs/ca-chain.cert.pem 2>&1 &
echo $! > ../server.pid
sleep 3

# Set up clients
cd ../client/scripts
./make_client polypose

# Go into polypose
cd ../../polypose

# getcert - username doesn't exist
./getcert -u rick -p morty
sleep 3

# check if certificate exists
FILE=certs/mycert.cert.pem
if test -f "$FILE"; then
    echo -e "-------------------------------GETCERT TEST 3 FAILED.-------------------------------\n" >> ../test_cases/very_secure_results.txt
else
    echo -e ' \xE2\x9C\x85\tGETCERT TEST 3 PASSED\t\xE2\x9C\x85 \n' >> ../test_cases/very_secure_results.txt
fi

# Clean up clients
cd ..
rm -rf polypose

# Clean up server
pkill -F server.pid
rm -f server.pid

# Clean up server
cd server/scripts
make clean
cd ..
rm -rf CA filesystem tmp
make clean

# Go back to test folder
cd ../test_cases