#!/bin/bash

# Go into security project folder
cd ..

# Setup server
cd server
make
cd scripts
./create-filesystem
./ca_setup
make
cd ..

# Run server
./https_server CA/intermediate/certs/www.finalproject.com.cert.pem CA/intermediate/private/www.finalproject.com.key.pem CA/intermediate/certs/ca-chain.cert.pem 2>&1 &
echo $! > ../server.pid
sleep 3

# Set up clients
cd ../client/scripts
./make_client polypose

# Go into polypose
cd ../../polypose

# sendmsg - bad client certificate
./getcert -u polypose -p lure_leagued
sleep 3

# bad certificate
cp ../test_cases/bad_client_cert.pem certs/bad_client_cert.pem
STR=$(./sendmsg -u polypose -m 'Dancing through life...' -c bad_client_cert.pem -r polypose)
sleep 3

# check if file 00000 doesnt exist
sent_message="../server/filesystem/polypose/pending/00000"
if test -f "$sent_message"; then
    echo -e "-------------------------------SENDMSG TEST 1 FAILED.-------------------------------\n" >> ../test_cases/very_secure_results.txt
else
    echo -e ' \xE2\x9C\x85\tSENDMSG TEST 1 PASSED\t\xE2\x9C\x85 \n' >> ../test_cases/very_secure_results.txt
fi

# Clean up clients
cd ..
rm -rf polypose

# Clean up server
pkill -F server.pid
rm -f server.pid

# Clean up server
cd server/scripts
make clean
cd ..
rm -rf CA filesystem tmp
make clean

# Go back to test folder
cd ../test_cases