#!/bin/bash

#run inside of a client docker 
umask 111 #make everything only executable

#create a prviliged user in the docker called server

#set perms on individual mailboxes
for DIR in filesystem; do 
chmod u=rwx,g=,o= $DIR $DIR/hashed_password $DIR/pending
chown root $DIR $DIR/hashed_password $DIR/pending
chown server $DIR $DIR/hashed_password $DIR/pending
done

# The mailergroup was made in make-mailbox users. Only this group will have access to the filesystem.
chown server filesystem
chmod u=rwx,g=,o= filesystem  

#similar permissions set for tmp
chown server tmp
chmod u=rx,g=rx,o=rx tmp

# Now, set the group and setgid for https_server to mailergroup
chown server https_server
chmod 111 https_server
chmod u+s https_server