#!/bin/bash

#Will set up a filesystem in the directory "filesystem"
mkdir ../tmp
mkdir ../filesystem
cd ../filesystem

#stored as name, hashed password, password
CTR=0
for token in `cat ../configs/hashed_passwords`; do
# username
  if [ $(($CTR % 3)) -eq "0" ]
  then
    mkdir $token
    cd $token
    mkdir pending
  fi
# hashed password
  if [ $(($CTR % 3)) -eq "1" ]
  then
    touch hashed_password
    echo -n "$token" > hashed_password #do not add newline
  fi
# password
  if [ $(($CTR % 3)) -eq "2" ]
  then
       cd ..
  fi
  ((CTR=CTR+1))
done
