#!/bin/bash

#Given the argument <dirname> will set up a filesystem there.
mkdir "$1"
cd "$1"

#stored as name, hashed password, password
i=0
for token in `cat hashed_passwords`; do
# username
  if [[ (($i % 5))-eq 0]]; then
    mkdir $token
    cd $token
  fi
# hashed password
  if [[ (($i % 5))-eq 0]]; then
    touch hashed_password
    echo "$token" > hashed_password.key.pem
  fi
# password
  if [[ (($i % 5))-eq 0]]; then
       exit 1
       cd ..
  fi
  ((i=i+1))
done

input=("ava" "addleness" "analects" "annalistic" "anthropomorphologically" "blepharosphincterectomy" "corector" "durwaun" "dysphasia" "encampment" "endoscopic" "exilic" "forfend" "gorbellied" "gushiness" "muermo" "neckar" "outmate" "outroll" "overrich" "philosophicotheological" "pockwood" "polypose" "refluxed" "reinsure" "repine" "scerne" "starshine" "unauthoritativeness" "unminced" "unrosed" "untranquil" "urushinic" "vegetocarbonaceous" "wamara" "whaledom")

for user in ${input[@]}
do
    mkdir $user
    
done
